import { etTime } from '../format.js'

const DATA_LABELS = {
  percentile: 'Move size vs 5-year history',
  divergence: 'Divergence vs sector and market',
  beta: 'Beta-adjusted expected move',
  sector: 'Sector ETF move',
}

function Evidence({ ev }) {
  if (ev.kind === 'headline') {
    const h = ev.headline
    return (
      <div className="evidence">
        <span className="chip" style={{ marginLeft: 0, marginRight: 6 }}>{h.id}</span>
        <a href={h.url} target="_blank" rel="noreferrer">{h.headline}</a>
        <div className="why">NYT · {etTime(h.pub_date)} · {ev.why}</div>
      </div>
    )
  }
  return (
    <div className="evidence">
      <span className="chip" style={{ marginLeft: 0, marginRight: 6 }}>data</span>
      {DATA_LABELS[ev.ref] ?? ev.ref}
      <div className="why">{ev.why}</div>
    </div>
  )
}

export default function Explanations({ exp }) {
  return (
    <section className="card">
      <div className="step">4 · Candidate explanations</div>
      <h2>What might explain it</h2>
      <p className="sub">Generated by Gemini from the data and headlines above. Every claim cites its evidence.</p>
      {!exp && <p className="loading">Gemini is weighing the evidence…</p>}
      {exp?.error && <p className="error">Couldn't generate explanations: {exp.error}</p>}
      {exp?.explanations?.map((e, i) => (
        <div className="exp" key={i}>
          <h3>{e.title}<span className="chip">{e.confidence} confidence</span></h3>
          <p>{e.summary}</p>
          {e.evidence.map((ev, j) => <Evidence key={j} ev={ev} />)}
        </div>
      ))}
      {exp?.caveat && <p className="caveat">{exp.caveat}</p>}
    </section>
  )
}
